import { KeyLabelIcon } from 'tangent-cc-lib';

export type Icon =
  | KeyLabelIcon
  | '123'
  | 'abc'
  | 'arrow_drop_down'
  | 'arrow_drop_up'
  | 'arrow_right'
  | 'article'
  | 'chevron_left'
  | 'chevron_right'
  | 'close'
  | 'code'
  | 'delete'
  | 'developer_board'
  | 'function'
  | 'help'
  | 'info'
  | 'keyboard'
  | 'kid_star'
  | 'left_panel_open'
  | 'map'
  | 'music_note_2'
  | 'open_in_new'
  | 'pause'
  | 'piano'
  | 'play_arrow'
  | 'print'
  | 'question_mark'
  | 'repeat'
  | 'replay'
  | 'settings'
  | 'thumb_up'
  | 'topic'
  | 'trending_up'
  | 'volume_off';
